puts "The students of my cohort at Makers Academy"
puts "------------------"
puts "Javier Silverio"
puts "Elliot Lewis"
puts "Ben Tillett"
puts "Vincent Koch"
puts "Michelle Ballard"
puts "Nick Roberts"
puts "Tatiana Soukiassian"
puts "Mervé Silk"
puts "Albert Vallerdu"
puts "Lovis Schultze"
puts "Chris Oatley"
puts "Spike Lindsey"
puts "Henry Stanley"
puts "Ruth Earle"
puts "Andy Gates"
puts "Marc Singh"
puts "Faisal Aydarus"
puts "Ethel Ng"
puts "Kevin Daniells"
puts "Maya Driver"
puts "Leopold Kwok"
puts "James McNeil"
puts "Jerome Pratt"
puts "David Wickes"